Lesson16
alabamaair/chuchu_mzfkr pull request #3
Opened 2016-12-25 21:13 UTC by alabamaair

2016-12-26 08:44 UTC, vkurennov requested changes

2016-12-26 08:44 UTC, vkurennov commented on app/controllers/railway_stations_controller.rb
> +    @railway_station.update_index_station(@route, params[:index_station], params[:arrival], params[:departure])
Для апдейта времени и порядкового номера лучше было бы сделать отдельные экшены

2016-12-26 08:44 UTC, vkurennov commented on app/controllers/searches_controller.rb
> +    common_routes = @start_station.routes & @end_station.routes
Вообще, лучше было бы всю логику вынести в отдельный класс Search (простой руби-класс), т.к. в контроллерах не должно быть бизнес-логики.

2016-12-26 08:44 UTC, vkurennov commented on app/models/railway_station.rb
> +      @station_route.arrival = arrival
Используя метод update, можно обновить все значения одной строкой. Но обновлять индекс и время в одном методе неудобно. Что если я хочу изменить только время или только индекс? Лучше разделить на 2 метода - один для индекса и один для времени (отправление и прибытие можно в одном методе редактировать)

2016-12-26 08:44 UTC, vkurennov commented on app/models/railway_station.rb
> +    t = station_route(route).try(:arrival)
используй более понятные имена переменных, например, time

2016-12-27 09:58 UTC, vkurennov approved these changes
Принято, но исправь замечания при выполнении следующего задания

2016-12-27 09:58 UTC, vkurennov commented on app/controllers/searches_controller.rb
> +    @end_station = RailwayStation.find(params[:end_station][:railway_station_id])
Поиск можно было бы тоже сделать в классе Search, передвая ему только id станций из параметров

2016-12-27 09:58 UTC, vkurennov commented on app/controllers/tickets_controller.rb
> +    @ticket.number = "TN#{Time.now.year}#{Time.now.month}#{Time.now.day}#{Array.new(4){rand(9)}.join}"
Генерация номера должна быть в коллбеках модели, а не в контроллере, т.к. объект не всегда может создаваться через контроллер. Ну и вообще, в контроллере должен быть минимум логики, остальное - в моделях.

2016-12-27 20:45 UTC, merged

2016-12-27 22:13 UTC, alabamaair commented on app/controllers/searches_controller.rb
> +    @end_station = RailwayStation.find(params[:end_station][:railway_station_id])
эти две переменные еще нужны для рендера _result тут же ниже.